# Generated by Django 4.2.7 on 2024-01-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdata',
            old_name='county',
            new_name='country',
        ),
    ]
